version: '3'

services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    networks:
      - my_inception
    build: ./requirements/mariadb
    volumes:
      - "db:/var/lib/mysql"
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306

  nginx:
    container_name: nginx
    hostname: nginx
    depends_on:
      - wordpress
    networks:
      - my_inception
    build: ./requirements/nginx
    restart: always
    volumes:
      - "wordpress:/var/www/html"
    ports:
      - 8080:8080
      - 443:443
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    image: wordpress
    hostname: wordpress
    depends_on:
      - mariadb
    networks:
      - my_inception
    build: ./requirements/wordpress
    volumes:
      - "wordpress:/var/www/html"
    env_file:
      - .env

networks:
  my_inception:

volumes:
  db:
  wordpress:

# docker-compose down && docker-compose build && docker-compose up -d